#########################################################
# Author: Aleita Train
# OSU ONLINE CS 496
# WINTER 2018
#########################################################

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: home.app

